### PR TITLE
Advance beaver from v0.4.0 to v0.6.0-rc.1

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
This release candidate should allow us to better specify the repository to which libmxnet packages will be uploaded.  It will likely be retagged as the final release without change.

* beaver v0.4.0(61aebb1)...v0.6.0-rc.1(274841c) (10 commits)
  > bintray: Add -C <component> option to upload
  > Allow passing beaver options via CLI
  > Merge tag v0.5.1 into v0.x.x v0.5.1
  > Clear release notes after release
  > Pass DFLAGS from beaver to docker container
  (...)

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
No plan to use the new option too in this same PR?

**Comment by joseph-wakeling-sociomantic** [comment]
Good call, I'll add a follow-up patch.

**Comment by joseph-wakeling-sociomantic** [comment]
OTOH, no harm in getting this patch in and tested in its own right, and following up in a separate PR.  So let's move forward like this for now.

**Comment by leandro-lucarella-sociomantic** [comment]
Maybe you just wanted to advance to a RC if the tests passed, but whatever works best for you :)

**Comment by joseph-wakeling-sociomantic** [comment]
Yea, it's what I'm going to do.  Will follow up shortly.

**Pull request merged**
