### PR TITLE
Merge stable 1.2.0 release of MXNet

### PR DESCRIPTION
**Pull request by jens-mueller-sociomantic**
https://github.com/apache/incubator-mxnet/releases/tag/1.2.0

When resolving the conflicts their version was picked all the time with
the only exception being `.gitmodules` which was manually merged and
`.github/PULL_REQUEST_TEMPLATE.md` to have it removed. To see our
changes diff against the MXNet 1.2.0 tag.

* 3rdparty/dlpack ()...10892ac(10892ac) (1 commits)
  > small fix to NEWS.md (#24)

* 3rdparty/dmlc-core ()...e9446f5(e9446f5) (1 commits)
  > fix memory leak (#386)

* 3rdparty/mkldnn ()...f5218ff4(f5218ff4) (1 commits)
  > api: c++: delete move ctor

* 3rdparty/mshadow ()...a8c650c(a8c650c) (1 commits)
  > remove definition when using f16c so nvcc can be turned off (#336)

* 3rdparty/nnvm ()...2bc5144(2bc5144) (1 commits)
  > [FRONTEND] DarkNet Yolo2 Frontend Support  (#377)

* 3rdparty/ps-lite ()...v1+144(a6dda54) (1 commits)
  > Merge pull request #132 from rahul003/cmake-typo

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
I don't understand why this branch is deemed to have conflicts: it fast-forwards just fine.

**Comment by jens-mueller-sociomantic** [comment]
You mean `git merge --ff 1.2.0` works for you without conflicts?

**Comment by joseph-wakeling-sociomantic** [comment]
No, I mean that pulling the merge commit from this PR works just fine.

**Comment by joseph-wakeling-sociomantic** [comment]
Ah, I see why: it's rebase and merge that is forbidden, a merge would work just fine.  So I think I can approve this and take it in just by pushing to v1.x.x.  I'll do that now.

**Review by joseph-wakeling-sociomantic — APPROVED** [review]

**Comment by jens-mueller-sociomantic** [comment]
> No, I mean that pulling the merge commit from this PR works just fine.

Yes, that should be the case. Should I rephrase the commit/PR message because it was misleading?

**Comment by jens-mueller-sociomantic** [comment]
Well, it's merged already. So I'll guess it was fine.

**Comment by joseph-wakeling-sociomantic** [comment]
Your commit message was fine.  The problem was on GitHub's side (to do with how their `Rebase and merge` button works).

**Pull request merged**
