### PR TITLE
Update beaver from v0.1.2 to v0.3.2

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
Despite jumping 2 minor versions, this update should be a no-op given the beaver setup that we use.

* beaver v0.1.2(f60fd6c)...v0.3.2(82f8c8f) (37 commits)
  > Fix spelling of BEAVER_DOCKER_IMG
  > bintray: Improve error message when -d is invalid
  > bintray: Fix typo in error message
  > codecov: Add prefix to all sent flags
  > codecov: Properly sanitize sent flags
  (...)

### CODE REVIEW

**Comment by jens-mueller-sociomantic** [comment]
What about the suggested move to a `beaver.Dockerfile` (see https://github.com/sociomantic-tsunami/beaver/releases/tag/v0.2.0). Does it not apply? Why?

**Comment by joseph-wakeling-sociomantic** [comment]
I don't think we _have_ to do that, but we can (and I will, after this patch lands).

**Comment by jens-mueller-sociomantic** [comment]
Can you mention this in the commit message?

**Comment by joseph-wakeling-sociomantic** [comment]
> Can you mention this in the commit message?

The beaver version upgrade doesn't bring any obligation to upgrade the dockerfile design.  It's generally not our practice to announce upcoming changes unless a patch is part of a series of strongly coupled changes.

**Comment by jens-mueller-sociomantic** [comment]
It does not hurt to write down a clarifying note. Because the migration instruction says

> You should move to use a `beaver.Dockerfile` unless you **really** need some
customization that is not supported by `beaver docker gen-dockerfile`.

To me this sounds like one should give an explanation for why one is not following it. Even though it just might say, planned to do later. Because it could also be the case no `beaver.Dockerfile` is going to be used (because of some unsupported customization).

**Comment by joseph-wakeling-sociomantic** [comment]
Updated 1st commit message, and added a follow-up patch to switch out the `Dockerfile` setup.

**Comment by joseph-wakeling-sociomantic** [comment]
> To me this sounds like one should give an explanation for why one is not following it.

I think that's the wrong way round.  The default, normal use-case for any non-breaking dependency upgrade is that one upgrades, then later switches to use new features.  It's the exceptions to this rule that should be explained (e.g. if there is a reason why one should NOT use the new features, or if there is a reason to switch immediately, such as a breaking change that must be dealt with).

What one could do, on an upgrade like this, is to open a separate issue for the desired new features, to make sure they don't get overlooked.  Or, as in this case, to immediately roll out the change in a follow-up patch.

**Comment by joseph-wakeling-sociomantic** [comment]
It can be useful, with submodule updates, to note the availability of important/desirable new features, but by or large one should not have to explain why one is NOT coupling a change together with the update.

For example, one does not typically need to announce in an update patch why one is not immediately switching out newly-deprecated functionality.

**Comment by jens-mueller-sociomantic** [comment]
I'll guess I read too much into the phrasing of the migration instruction. It doesn't say that you have to do that change immediately or mention how to approach it.

**Review by jens-mueller-sociomantic — APPROVED** [review]

**Pull request merged**
