### PR TITLE
Merge stable 1.1.0 release of MXNet

### LINKED ISSUE #235: train.rec  test.rec for cifar100
where can i find train.rec and test.rec for cifar100

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
https://github.com/apache/incubator-mxnet/releases/tag/1.1.0
    
A quite extended amount of manual work was needed here to resolve all the conflicts, almost none due to the tsunami fork!

Some diffs seemed to survive the merge, and were fixed via manually checking out the files in question from the upstream 1.1.0 tag.

* 3rdparty/cub ()...05eb57fa(05eb57fa) (1 commits)
  > Merge pull request #1 from ptrendx/update

* 3rdparty/googletest ()...release-1.8.0(ec44c6c) (1 commits)
  > Merge pull request #821 from mazong1123/master

* 3rdparty/openmp ()...37c7212(37c7212) (1 commits)
  > Merging r317115:

* 3rdparty/cub ()...05eb57fa(05eb57fa) (1 commits)
  > Merge pull request #1 from ptrendx/update

* 3rdparty/googletest ()...release-1.8.0(ec44c6c) (1 commits)
  > Merge pull request #821 from mazong1123/master

* 3rdparty/openmp ()...37c7212(37c7212) (1 commits)
  > Merging r317115:

* dmlc-core 87b7ffa(87b7ffa)...6389c10(6389c10) (20 commits)
  > Fix symbol demangling on stacktraces under Linux. (#356)
  > Add more environment variables to support 3rd-party S3 implementations (#354)
  > add qid as ranklib format (#317)
  > Make choice of archiver configurable (#352)
  > Fix warnings in unittest_lockfree.cc, fix travis CI (#347)
  (...)

* mshadow 2d7780c(2d7780c)...16ac8cd(16ac8cd) (5 commits)
  > Add fully qualified type on define default_real_t (#317)
  > fix AddTakeGradLargeBatch for CPU. close #235 (#316)
  > fix float16 min and max values (#315)
  > [Windows] make Packet::size constexpr (#313)
  > add GetRndEngine (#308)

* nnvm e4a138a(e4a138a)...7a052d6(7a052d6) (3 commits)
  > [SYMBOL] Add __iter__ and GetChildren for symbol (#268)
  > API call to get symbol output count (#270)
  > [FRONTEND] Fix mxnet multi outputs (#271)

### CODE REVIEW

**Comment by jens-mueller-sociomantic** [comment]
What do you mean by manual work? If there is a conflict the upstream wins (except for tsunami related changes).

**Comment by jens-mueller-sociomantic** [comment]
I verified the release locally. Looks good to me.

**Review by jens-mueller-sociomantic — APPROVED** [review]

**Comment by joseph-wakeling-sociomantic** [comment]
> What do you mean by manual work? If there is a conflict the upstream wins (except for tsunami related changes).

I think what must have happened is _different_ changes in the 1.0 and 1.1 upstream branches, that didn't conflict but produced noticeable differences in the codebase.  I made a choice to resolve those differences, so that we are dealing with a vanilla copy of upstream MXNet 1.1.0.

**Comment by jens-mueller-sociomantic** [comment]
I see. In the end we want to make sure that our 1.1.0 matches upstream.

**Pull request merged**
