### PR TITLE
Use FUN.autodepends to determine libmxnet package dependencies

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
This should be more robust than the previous hardcoded dependencies.

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
This results in:

```
Depends: libc6, libgcc1, libgfortran3, libgomp1, libopenblas-base, libquadmath0, libstdc++6
```

as compared to the previous package definition with hardcoded dependencies:

```
Depends: libc6, libstdc++6, libopenblas-base
```

**Comment by joseph-wakeling-sociomantic** [comment]
Note: it's deliberate to only check `libmxnet.so` for dependencies, since `ldd` won't work on `libmxnet.a`.

**Comment by joseph-wakeling-sociomantic** [comment]
That said: `ldd ./lib/*` seems to work if I run it locally, but if I put

```
depends = FUN.autodeps(['*'], path='./lib'),
```

into `libmxnet.pkg`, I get a build error:

```
Running command: ['ldd', './lib/*']
ldd: ./lib/*: No such file or directory
Error: can't load package definition file 'mxnet/pkg/libmxnet.pkg'

Traceback (most recent call last):
  File "mxnet/pkg/libmxnet.pkg", line 24, in <module>
    depends = FUN.autodeps(['*'], path='./lib'),
  File "mxnet/makd/mkpkg", line 142, in autodeps
    for f in self._expand_list(fnames, path)]
  File "mxnet/makd/mkpkg", line 142, in <listcomp>
    for f in self._expand_list(fnames, path)]
  File "mxnet/makd/mkpkg", line 117, in _parse_cmd
    output = subprocess.check_output(cmd).decode(sys.stdin.encoding)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldd', './lib/*']' returned non-zero exit status 1
```

**Comment by joseph-wakeling-sociomantic** [comment]
An alternative approach based on @mihails-strasuns-sociomantic's suggestion to use `os.listdir`:

```
from os import listdir

libdir = './lib'
libs = listdir(libdir)

depends = FUN.autodeps(libs, path=libdir)
```

... but this fails because `ldd ./lib/libmxnet.a` returns 1.

**Comment by jens-mueller-sociomantic** [comment]
Why don't you want `depends = FUN.autodeps(['libmxnet.so'], path='./lib')`? What is wrong about the specific binary?

**Comment by joseph-wakeling-sociomantic** [comment]
OK, I think I have an improved mechanism, which actually works this time.  See `squash!` patch.

**Comment by joseph-wakeling-sociomantic** [comment]
> Why don't you want depends = FUN.autodeps(['libmxnet.so'], path='./lib')? What is wrong about the specific binary?

Want to avoid hardcoding one specific library name and catch all dependencies from all dynamic libs included in the package.

**Comment by jens-mueller-sociomantic** [comment]
I've seen it. What is the need for it?

**Comment by joseph-wakeling-sociomantic** [comment]
To ensure that the package definition is robust to mxnet including more shared libraries, or changing the `.so` file name.

**Comment by jens-mueller-sociomantic** [comment]
If you consider this to be likely. I could live with the building of the package to fail in that case. Because if the library is renamed or new libraries added any application needs to change its linking.

**Comment by joseph-wakeling-sociomantic** [comment]
I've broken things down into 2 different patches: one to update how the `libs` included in the package are determined, the other to start using `FUN.autodepends`.

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
LGTM

**Pull request merged**
