### PR TITLE
Remove upstream GitHub PR template

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
This isn't suitable for our own issue reporting concerns, which will be 99% to do with the deb package rather than submitting contributions to MXNet itself.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Maybe change it to some text asking people to report issues upstream instead?

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic this isn't an issue template (we already removed that).  This adds a bunch of automatic text every time one submits a PR (which we do want to do).

**Comment by joseph-wakeling-sociomantic** [comment]
(We also want to be able to submit issues here, but they'll be about the package generation, not upstream MXNet issues.)

**Comment by leandro-lucarella-sociomantic** [comment]
> (We also want to be able to submit issues here, but they'll be about the package generation, not upstream MXNet issues.)

Yes, I mean clarifying exactly that when a new issue is created. But you could also add a [CONTRIBUTING](https://github.com/blog/1184-contributing-guidelines) file.

**Comment by joseph-wakeling-sociomantic** [comment]
I'm running with the assumption that, for now at least, we're unlikely to get external issue reports and PRs.  But we can revisit that if it turns out to be wrong.

**Comment by joseph-wakeling-sociomantic** [comment]
Can we take this in, and follow up on appropriate contributor instructions as a separate issue?

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, I never meant to block this PR, it was just a side discussion.

**Pull request merged**
