### PR TITLE
Merge stable 1.3.1 release of MXNet

### PR DESCRIPTION
**Pull request by jens-mueller-sociomantic**
https://github.com/apache/incubator-mxnet/releases/tag/1.3.1

This updates to MXNet 1.3.1. We are skipping 1.2.x because they
indirectly reference missing commits. The update to 1.3.0 is skipped
because there is already the patched version 1.3.1 available.

The conflicts in `.gitmodules` are manually resolved to keep our
beaver and makd dependencies. For all other conflicts their version was
picked all the time.

To see our changes with respect to upstream MXNet diff against the MXNet
1.3.1 tag, i.e., `git diff 1.3.1..HEAD`.

By default MXNet 1.3.1 integrates Intel MKL-DNN. For now we disable it because
we currently don't need it.

### CODE REVIEW

**Comment by jens-mueller-sociomantic** [comment]
We probably want to remove `.codecov.yml` from our repository.

**Comment by jens-mueller-sociomantic** [comment]
The diff against 1.3.1 mentions changes for `tests/python/gpu/test_kvstore_gpu.py` which should not be there. I try to figure out how they ended up there.

**Comment by jens-mueller-sociomantic** [comment]
Removed the changes for `tests/python/gpu/test_kvstore_gpu.py` because the merge commit shouldn't have touched this file.

**Comment by stefan-koch-sociomantic** [comment]
I cannot meaningfully review this.
If it does not break anything on your side, it's good to go.

**Review by stefan-koch-sociomantic — APPROVED** [review]
If it does not break anything on your side I am fine with those changes.

**Comment by jens-mueller-sociomantic** [comment]
Tested it and looks good.

**Pull request merged**
