### PR TITLE
Provide beaver with correct location of deb packages to upload

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
Fixes https://github.com/sociomantic-tsunami/mxnet/issues/3.

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
I just noticed in the build log:

> Created package {:path=>"/home/travis/build/sociomantic-tsunami/mxnet/build/devel/pkg/libmxnet_0e4bba5fd-trusty_amd64.deb"}

Should I be using `make -f makd/Makd.mak F=production pkg` ... ? :-)

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
> Should I be using make -f makd/Makd.mak F=production pkg ... ? :-)

You could, but for packages it doesn't have any impact (although for now, to be more future proof it might be an option).

**Comment by joseph-wakeling-sociomantic** [comment]
OK, done.  Do I understand right that (say) if in future we introduced a `Build.mak` then makd would automatically pick up on it from this call?

**Comment by leandro-lucarella-sociomantic** [comment]
No, I was meaning in case packaging at some point includes some metadata to mention if it's a production or devel build :)

**Comment by joseph-wakeling-sociomantic** [comment]
Ah yes, I forgot that was a feature request.  TBH in that case we should probably be looking at a different setup anyway ... but let's burn that bridge when we come to it ;-)

**Comment by joseph-wakeling-sociomantic** [comment]
Does the overall changeset SLGTY?

**Pull request merged**
